title: AICD-1 Supplementary
description: Supplementary Resource for Nature Comment on Artificial Intelligence Medicine

# これがポイント！
remote_theme: just-the-docs/just-the-docs

# ナビゲーション（変わらず）
nav:
  - Home: index.md
  - Full Classification:
    　- Overview: classification/index.md
    　- Chapter 1: classification/chapter1.md
    　- Chapter 2: classification/chapter2.md
    　- Chapter 3: classification/chapter3.md
    　- Chapter 4: classification/chapter4.md
    　- Chapter 5: classification/chapter5.md
    　- Chapter 6: classification/chapter6.md
    　- Chapter 7: classification/chapter7.md
    　- Chapter 8: classification/chapter8.md
    　- Chapter 9: classification/chapter9.md
  - Case Studies: case-studies.md
  - Diagnostic Algorithms: diagnostics.md
  - Evaluation Metrics: evaluation.md
  - Glossary: glossary.md
  - Download Center: download.md
  - References / Citing this Resource: references.md

