title: AICD-1 Supplementary
description: Supplementary Resource for Nature Comment on Artificial Intelligence Medicine
theme: just-the-docs

# ナビゲーション順
nav:
  - Home: index.md
  - Full Classification: classification.md
  - Case Studies: case-studies.md
  - Diagnostic Algorithms: diagnostics.md
  - Evaluation Metrics: evaluation.md
  - Glossary: glossary.md
  - Download Center: download.md
  - References / Citing this Resource: references.md
