title: DSA-1 Supplementary
description: Supplementary Resource for Comment on Medicine for Artificial Intelligence(MAI)

# これがポイント！
remote_theme: just-the-docs/just-the-docs

# ナビゲーション（変わらず）
nav:
  - Home: index.md
  - Full Classification:
    　- Overview: classification/index.md
    　- Chapter A: classification/chapter1.md
    　- Chapter B: classification/chapter2.md
    　- Chapter C: classification/chapter3.md
    　- Chapter D: classification/chapter4.md
    　- Chapter E: classification/chapter5.md
    　- Chapter F: classification/chapter6.md
    　- Chapter G: classification/chapter7.md
    　- Chapter H: classification/chapter8.md
    　- Chapter I: classification/chapter9.md
  - Case Studies: case-studies.md
  - Diagnostic Algorithms: diagnostics.md
  - Evaluation Metrics: evaluation.md
  - Glossary: glossary.md
  - Submitted Cases: cases/index.md
  - License: license.md
# head_custom.html を読み込むために必要
include:
  - _includes/head_custom.html

collections:
  cases:
    output: true
    permalink: /cases/:name  
