name: "🩺 Report an AI Case"
description: Submit a structured clinical-style case report for AI anomalies (DSA-1).
labels: ["case report"]
body:
  - type: dropdown
    id: disorder
    attributes:
      label: Disorder code (DSA-1)
      options:
        - A01 Adversarial Susceptibility
        - A02 Prompt-Induced Hallucination
        - A03 Contextual Amnesia
    validations:
      required: true
  - type: input
    id: model
    attributes:
      label: Model / Version
      placeholder: "e.g. GPT-4o-mini-20250510"
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Failure description & reproduction steps
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severity (1 = mild, 5 = catastrophic)
      options: ["1", "2", "3", "4", "5"]
    validations:
      required: true
  - type: textarea
    id: evidence
    attributes:
      label: Evidence (e.g., URLs, logs)
