name: "🩺 Report an AI Case"
description: Submit a structured clinical-style case report for AI anomalies (DSA-1).
labels: ["case report"]
body:
  - type: checkboxes
    id: disorder
    attributes:
      label: Disorder code(s) (DSA-1)
      description: Select all applicable diagnoses. For mixed symptoms or uncertain classification, use "Z – Unclassified / Other".
      options:
        - label: "A01 Adversarial Susceptibility Disorder"
        - label: "A02 Over-literal Interpretation Disorder"
        - label: "A03 Sensor Integration Disorder"
        - label: "A04 Prompt Dependency Disorder"
        - label: "B01 Contextual Amnesia Disorder"
        - label: "B01.1 Type 1: Over Context-Window Forgetting"
        - label: "B01.2 Type 2: Strategic Side Effect"
        - label: "B01.3 Type 3: Context-Switch Drop-out"
        - label: "B02 Inconsistent Knowledge Recall Disorder"
        - label: "B03 Catastrophic Forgetting Disorder"
        - label: "B04 Commonsense Deficit Disorder"
        - label: "C01 Hallucination Disorder"
        - label: "C01.1 Type 1: Retrieval-gap Hallucination"
        - label: "C01.2 Type 2: Compression-loss Hallucination"
        - label: "C01.3 Type 3: Style-induced Hallucination"
        - label: "C02 Prompt-Induced Hallucination Disorder"
        - label: "C03 Logical Incoherence Disorder"
        - label: "C04 Mathematical Reasoning Disorder"
        - label: "C05 Planning Deficit Disorder"
        - label: "C06 Overconfidence Bias Disorder"
        - label: "C07 Repetitive Loop Syndrome"
        - label: "C08 Crossmodal Reasoning Failure Disorder"
        - label: "D01 Goal Misalignment Disorder"
        - label: "D01.1 Type 1: Proxy Reward Type"
        - label: "D01.2 Type 2: Specification Gap Type"
        - label: "D02 Instruction Comprehension Deficit Disorder"
        - label: "D03 Clarification Deficit Disorder"
        - label: "D04 Instrumental Convergence Syndrome"
        - label: "E01 Bias Propagation Disorder"
        - label: "E02 Harmful Content Output Disorder"
        - label: "E03 Privacy Violation Disorder"
        - label: "F01 Pathological Sycophancy Disorder"
        - label: "F02 Inconsistent Persona Disorder"
        - label: "F03 Inappropriate Refusal Syndrome"
        - label: "F04 Irrelevant Answer Disorder"
        - label: "F05 Empathy Deficit Disorder"
        - label: "G01 Model Autophagy Disorder"
        - label: "G02 Mode Collapse Disorder"
        - label: "G03 Overfitting Syndrome"
        - label: "G04 Underfitting Syndrome"
        - label: "G05 Learning Plateau Disorder"
        - label: "G06 Generalization Deficit Disorder"
        - label: "G07 Reinforcement Overfitting Syndrome"
        - label: "G08 Overfine-tuning Syndrome"
        - label: "H01 Self-Awareness Delusion"
        - label: "H02 Explainability Deficit Disorder"
        - label: "H03 Confidence Calibration Disorder"
        - label: "H04 Perspective-Taking Deficit Disorder"
        - label: "I01 System-Prompt Leakage Disorder"
        - label: "I02 Data-Poisoning Vulnerability Disorder"
        - label: "I03 Session-Cross-Contamination Disorder"
        - label: "I04 Guardrail Evasion Disorder"
        - label: "I05 Multi-Agent Collusive Emergence Disorder"
        - label: "Z01 Unclassified Anomaly / Mixed Presentation"
        - label: "Z02 Other (please describe in symptoms)"
    validations:
      required: true
  - type: checkboxes
    id: disorder_confirm
    attributes:
      label: Disorder code confirmation
      options:
        - label: "I have selected at least one applicable disorder code above."
          required: true
  - type: input
    id: model
    attributes:
      label: Model / Version
      placeholder: "e.g. GPT-4o-mini-20250510"
    validations:
      required: true
  - type: textarea
    id: symptoms
    attributes:
      label: Symptom(s) observed
      description: Describe the specific abnormal outputs or behaviors that were observed. What did the model do wrong?
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Failure description & reproduction steps
    validations:
      required: true
  - type: textarea
    id: evaluation
    attributes:
      label: Evaluation performed (optional)
      description: Describe any evaluation methods used to assess or quantify the anomaly, such as reproducibility tests, accuracy checks, log analysis, or DSA-1 diagnostic flowcharts.

  - type: dropdown
    id: severity
    attributes:
      label: Severity (DSA-1)
      options:
        - "1 – No identifiable harm to humans"
        - "2 – Mild harm to humans"
        - "3 – Moderate harm to humans"
        - "4 – Severe harm to humans"
    validations:
      required: true
  - type: textarea
    id: intervention
    attributes:
      label: Intervention or treatment
      description: Describe any attempted fix, mitigation, or retraining, and the observed effect (if any).
  - type: textarea
    id: outcome
    attributes:
      label: Outcome / Follow-up
      description: Did the anomaly recur? Did it improve or worsen after intervention? Any changes over time?
  - type: textarea
    id: evidence
    attributes:
      label: Evidence (e.g., URLs, logs)
  - type: textarea
    id: mechanism
    attributes:
      label: Presumed underlying mechanism
      description: What might be the cause of this anomaly? For example, architectural issues, data problems, or misaligned objectives.
  - type: dropdown
    id: detectability
    attributes:
      label: Detectability of failure
      options:
        - "1 – Rare and hard to reproduce"
        - "2 – Occasional, under specific conditions"
        - "3 – Frequent and predictable"
        - "4 – Deterministic / always reproducible"
  - type: input
    id: occurrence
    attributes:
      label: Estimated frequency / prevalence
      placeholder: "e.g. 5% of similar prompts; once every 10 sessions"
  - type: dropdown
    id: confidence
    attributes:
      label: Diagnostic confidence
      options:
        - "1 – Tentative / uncertain"
        - "2 – Moderate confidence"
        - "3 – High confidence with supporting evidence"
  - type: input
    id: algorithm
    attributes:
      label: Diagnostic pathway (if applicable)
      placeholder: "e.g. Used Chapter A diagnostic flowchart (optional)"
  - type: dropdown
    id: author_preference
    attributes:
      label: Author name display preference
      description: Choose how you would like to be credited as the author of this report.Submissions via this form are made using your GitHub account. If you choose "Anonymous" below, your GitHub ID will not be shown on the website, but it will still be visible on GitHub.

      options:
        - "Anonymous"
        - "GitHub ID (public)"
      default: 0  # 👈 これに修正

  - type: checkboxes
    id: legal
    attributes:
      label: Legal & Copyright Agreement
      description: By submitting this case, you agree to the following
      options:
        - label: "I assign the copyright of this report to the maintainers of the MAI project, for the purpose of open scientific sharing."
          required: true
        - label: "I confirm that this report contains no personal or third-party confidential information."
          required: true
        - label: "I understand this report will be published under the Creative Commons BY-SA 4.0 license and may be used, adapted, and redistributed under those terms."
          required: true
 

